config/routes.rb
ProductGallery::Application.routes.draw do
  resources :pictures

  resources :products

  root :to => 'products#index'

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.new_record?
        can :index, Product
        can :show, Product
      else
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
#encoding: utf-8
class Picture < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :product_id, :attachment

  belongs_to :product

  has_attached_file :attachment, :styles => { large: '600x600>', medium: '300x300>', thumb: '100x100>' }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/

  validate :check_dimensions

  def check_dimensions
    dim = {x: 800, y: 600}
    temp_file = attachment.queued_for_write[:original]
    unless temp_file.nil?
      dimensions = Paperclip::Geometry.from_file(temp_file)
      width = dimensions.width
      height = dimensions.height
      if width != dim[:x] && height != dim[:y]
        errors.add(:attachment, "debe ser de #{dim[:x]}x#{dim[:y]} la imágen que seleccionó mide #{width.to_i.to_s}x#{height.to_i.to_s}")
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description

  has_many :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  private
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to product_path(@picture.product), notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :authenticate_scope!
  skip_load_and_authorize_resource

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  skip_load_and_authorize_resource

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>ProductGallery</title>
  <%= stylesheet_link_tag    'application', :media => "all" %>
  <%= yield :asset_stylesheet %>
  <%= javascript_include_tag 'application' %>
  <%= yield :asset_javascript %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-bottom: 30px; padding-top: 70px;">

<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', root_path %></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!--
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Opciones <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= link_to 'Registrar nuevo usuario', new_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Editar cuenta', edit_user_registration_path %></li>
                <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :method=>'delete' %></li>

            <% else %>
                <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
            <% end %>
            <% if user_signed_in? %>
                <li><%#= link_to 'Users', users_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container">

  <% flash.each do |key, msg| %>
      <div class="alert alert-<%= key %> alert-dismissable auto-remove">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p><%= msg %></p>
      </div>
  <% end %>
  <div class="row">

    <%= yield %>
  </div>

  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>© 2014 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture, html: { class: 'form-horizontal' }) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :product_id, value: params[:product_id] %>
  <div class="form-group">
    <%= f.label :attachment, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
        <%= f.file_field :attachment, autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :class => 'btn btn-primary'%>
    </div>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.product.description %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>Imágen nueva</h1>

<%= render 'form' %>

<%= link_to 'Regresar', products_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @picture.product %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/products/_form.html.erb
<%= form_for(@product, html: { class: 'form-horizontal' }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: 'form-control', placeholder: 'Descripción', autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :class => 'btn btn-primary'%>
      </div>
    </div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Productos</h1>
<!--

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.description %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Create picture', new_picture_path(product_id: product.id) %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
-->


<div class="row">
  <% @products.each do |product| %>
      <div class="col-lg-3 col-md-4 col-xs-6" style="text-align: center">
        <% if product.pictures.count > 0 %>
            <%= link_to product do %>
                <%= image_tag product.pictures.first.attachment(:medium), class: 'img-circle', style: 'width: 140px; height: 140px' %>
            <% end %>
        <% elsif can? :new, Picture %>
            <%= link_to '<i class="fa fa-cloud-upload fa-5x" style="width: 140px; height: 140px; text-align: center; padding: 30px 0px"></i>'.html_safe, new_picture_path(product_id: product.id), title: 'Cargue una imágen para el producto' %>
        <% else %>
           <i class="fa fa-ban fa-5x" title="Imágen no disponible" style="width: 140px; height: 140px; text-align: center; padding: 30px 0px"></i>
        <% end %>
        <h2><%= product.description %></h2>
        <p>
          <%= pluralize(product.pictures.count, 'imágen') %>
          <% if can? :new, Picture %>
              <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_picture_path(product_id: product.id), title: 'Cargue una imágen para el producto' %>
          <% end %>
        </p>

        <p><%= link_to 'Ver detalles >>', product, class: 'btn btn-default' %></p>
      </div><!-- /.col-lg-4 -->
  <% end %>
</div>

<% if can? :new, Product %>
    <%= link_to 'Crear producto', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>Producto nuevo</h1>

<%= render 'form' %>

<%= link_to '<< Regresar', root_path, class: 'btn btn-default' %>

app/views/products/show.html.erb
<% content_for :asset_javascript do %>
    <%= stylesheet_link_tag 'carousel' %>
<% end %>
<!--
<p>
  <b>Description:</b>
  <%#= @product.description %>
  <%# @product.pictures.each do |picture| %>
    <%#= image_tag picture.attachment.url(:thumb) %>
  <%# end %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
-->

<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @product.pictures.each_with_index do |picture, index| %>
        <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% @product.pictures.each_with_index do |picture, index| %>
        <div class="item <%= 'active' if index == 0 %>">
          <%= image_tag picture.attachment.url(:original) %>
          <div class="container">
            <div class="carousel-caption">
              <h1><%= @product.description %></h1>
              <!--<h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code>
                URL, the "next" and "previous" Glyphicon buttons on the left and right
                might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>-->
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->

<%= link_to '<< Regresar', root_path, class: 'btn btn-default' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>